# EnvVar2.yml playbook

---
- name: Insert envVar using Ansible
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Insert line in .env file"
      ansible.builtin.lineinfile:
        path: C:/Users/P432884/OneDrive - Nationwide Building Society/Desktop/Hello-world-challenge/.env
        regexp: '^MESSAGE='
        line: MESSAGE=Hello World!

    - name: "Echo .env"
      ansible.builtin.debug:
        msg: " {{lookup('ansible.builtin.file', 'C:/Users/P432884/OneDrive - Nationwide Building Society/Desktop/Hello-world-challenge/.env') }}"

# ERROR MESSAGE WHEN RUNNING PLAYBOOK:
# TASK [Insert line in .env file] ****************************************************************************************
# fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Destination C:/Users/P432884/Desktop/Hello-world-challenge does not exist !", "rc": 257}


# EnvVar.yml playbook

# ---
# - name: read env var stored locally
#   hosts: 127.0.0.1
#   connection: local
#   environment:
#     EnvVar: Hello_World_!

#Cannot locate EnvVar


# ---
# - name: Insert envVar using Ansible
#   hosts: 127.0.0.1
#   connection: local
#   tasks:
#     - name: "Insert line in .env iile"
#       ansible.builtin.lineinfile:
#         path: //wsl$/Ubuntu/home/p432884
#         regexp: '^MESSAGE='
#         line: MESSAGE=Hello World!

#     - name: "Echo .env"
#       ansible.builtin.debug:
#         msg: "{{ lookup('ansible.builtinfile', '//wsl$/Ubuntu/home/p432884') }}"

# Same error message